return {
  { "rktjmp/lush.nvim" },
  { "arzg/vim-colors-xcode" },
  { "sainnhe/gruvbox-material" },
  { "gruvbox-community/gruvbox" },
  { "folke/tokyonight.nvim" },
  { "sindrets/material.nvim" },
  { "sindrets/rose-pine-neovim", name = "rose-pine" },
  { "mcchrish/zenbones.nvim", dependencies = "rktjmp/lush.nvim" },
  { "sainnhe/everforest" },
  { "Cybolic/palenight.vim" },
  { "olimorris/onedarkpro.nvim", branch = "main" },
  { "NTBBloodbath/doom-one.nvim" },
  { "catppuccin/nvim", name = "catppuccin" },
  { "sindrets/dracula-vim", name = "dracula" },
  { "projekt0n/github-nvim-theme" },
  { "rebelot/kanagawa.nvim" },
  { "sindrets/oxocarbon-lua.nvim" },
  { "nyoom-engineering/oxocarbon.nvim" },
  { "EdenEast/nightfox.nvim" },
  { "kvrohit/mellow.nvim" },
}
